### ISSUE TITLE
Mock a single interface with go:gen

### ISSUE THREAD

**Issue by jriquelme** [xeger/mongoose#1]
Hi @xeger, I got here from https://github.com/vektra/mockery/issues/77 :+1: 

I wonder if it would be possible to generate mocks using go:gen "annotations" for a specific interface. I have a large project containing many interfaces with comments as below:

```
//go:generate mockery -inpkg -case=underscore -name TripRepository
type TripRepository interface {
...
}
```

Would be great being able to migrate to Mongoose keeping the same strategy to generate mocks.

**Comment by xeger** [comment]
Shouldn't be hard; IIRC, golang code-gen is pretty straightforward. I'm
away from my computer this weekend, but I'll look into it during the week.

**Comment by xeger** [comment]
I can add support for go generate, but there are a few caveats.

First, the easy part: detecting when mongoose has been invoked by generate, and automatically inferring that we should use the working dir as our one-and-only directory of source files. That's a cinch.

To implement a `-name` flag as Mockery has, is also fairly easy; however, due to the way mongoose works, it must parse _every_ file in the package even if it is only mocking some interfaces. This is a key to correctness, because your interface may use types or constants that are defined in other source files.

If all of your interfaces are defined in a single file, then you can decorate it with a `go:generate` comment, but of course your matching pattern would need to include the name of every interface in that file.

If your interfaces are defined in _separate_ files, then `go generate` will end up invoking `mongoose` several times (once per file) and mongoose will parse the entire package on every invocation; this will be much slower than invoking mongoose on the whole directory.

Neither of these seems ideal to me. I'll prototype something for you to try; let me know if it works for you, or whether it's too cumbersome.

**Comment by xeger** [comment]
@jriquelme, I've added support on the `go-generate` branch of mongoose. Please checkout that branch under `$GOPATH/github.com/xeger/mongoose` and then `make install` (or just `go install github.com/xeger/mongoose` if you prefer).

As an example of using go:generate with Testify bindings, see [the integration test](https://github.com/xeger/mongoose/blob/go-generate/test/testify/generate/generated.go#L3).

There are a few differences vs. your current `mockery` command line. To be specific:

1) You need `-mock testify` to ask Mongoose to use the Testify framework
2) There is no need for `-inpkg`; this is Mongoose's default behavior
3) There is no need for `-case=underscore`; this is Mongoose's default (and only) naming pattern

I've implemented the `-name` flag exactly as Testify has it, but do keep in mind my caveats about slowing down mock generation.

Let me know whether or not this works for you. If all goes well, I'll merge to master.

**Comment by jriquelme** [comment]
@xeger, the branch works perfectly, thanks.

**Comment by xeger** [comment]
Cool; merged to master.
